""" Add detections table

Revision ID: 5fb7cd383f28
Revises: 09ae62157f86
Create Date: 2026-03-13 02:40:18.724112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fb7cd383f28'
down_revision: Union[str, None] = '09ae62157f86'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_type', sa.String(), nullable=False),
    sa.Column('vehicle_confidence', sa.Float(), nullable=True),
    sa.Column('plate_text', sa.String(length=10), nullable=False),
    sa.Column('plate_confidence', sa.Float(), nullable=True),
    sa.Column('plate_bbox', sa.JSON(), nullable=True),
    sa.Column('original_image_s3_key', sa.String(), nullable=False),
    sa.Column('cropped_vehicle_s3_key', sa.String(), nullable=True),
    sa.Column('cropped_plate_s3_key', sa.String(), nullable=True),
    sa.Column('is_allowed', sa.Boolean(), nullable=True),
    sa.Column('allowed_car_id', sa.Integer(), nullable=True),
    sa.Column('processing_time_ms', sa.Float(), nullable=True),
    sa.Column('source', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['allowed_car_id'], ['allowed_cars.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detections_id'), 'detections', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detections_id'), table_name='detections')
    op.drop_table('detections')
    # ### end Alembic commands ###
